### ISSUE TITLE
Configuration file was corrupted and couldn't be loaded

### ISSUE THREAD

**Issue by SphereII** [Turbero/7DTD-Mods-Desktop#1]
Downloaded latest, and tried to run. It poroduced three files, 7D2D_Mods_desktop.conf, _Modlets, and _Quests. Then threw an error: "Configuration file was corrupted and couldn't be loaded. Delete to continue? Choose yes closes the app, as does No.

Attached is  zip file of the three errors produced.

[Github.zip](https://github.com/Turbero/7DTD-Mods-Desktop/files/4156745/Github.zip)

**Comment by Turbero** [comment]
Right now I downloaded the app from the link and pasted your 3 files before opening for first time. The tool came up without issues.

Just in case, I took a different approach to find and read files and also added a log to print out errors and spot the issue. New version: **1.0.0.1**

Please download it and let me know: [https://7dtdmodsdesktop.com/download.php](url)

**Comment by Turbero** [comment]
Right now I downloaded the app from the link and pasted your 3 files before opening for first time. The tool came up without issues.

Just in case, I took a different approach to find and read files and also added a log to print out errors and spot the issue. New version: **1.0.0.1**

Please download it and let me know: https://7dtdmodsdesktop.com/download.php

**Comment by SphereII** [comment]
Similar results. The logs contains:

Feb 04, 2020 10:30:12 PM org.turbero.sevendtd.modsdesktop.service.LoggerManager <init>
INFO: Welcome
Feb 04, 2020 10:30:12 PM org.turbero.sevendtd.modsdesktop.service.LoggerManager <init>
SEVERE: Welcome
Feb 04, 2020 10:30:15 PM org.turbero.sevendtd.modsdesktop.modletorganiser.swing.config.ModsOrganiserConfig loadSavedProfiles
SEVERE: null

**Comment by Turbero** [comment]
I have downgraded the minimum version for Java, enhanced the log and printed out some properties to get some clue. 

New version: **1.0.0.2**

Please download it and let me know how it goes: https://7dtdmodsdesktop.com/download.php

**Comment by SphereII** [comment]
Please find attached Log.

[7DTD_Mods_Desktop.log](https://github.com/Turbero/7DTD-Mods-Desktop/files/4161379/7DTD_Mods_Desktop.log)

**Comment by Turbero** [comment]
Ok I wasn't taking into consideration the chance of having incorrect values in the ModInfo.xml file. I was assuming I would always find Name, Description, Author and Version.

I'll upload fix shortly.

(PD: Your feedback is priceless. Thanks in advance)

**Comment by Turbero** [comment]
New version: **1.0.0.3**

https://7dtdmodsdesktop.com/download.php

Let me know if you finally manage to open the tool.

**Comment by SphereII** [comment]
Yes, the application starts now.

**Comment by Turbero** [comment]
Hurray! I'll close this and feel free to open more if needed.

Many thanks again for your feedback!
