### ISSUE TITLE
Built-In entities modlet has issues

### ISSUE THREAD

**Issue by SphereII** [Turbero/7DTD-Mods-Desktop#2]
The build-in modlet to disable animal bears, snakes, etc all get written to entities.xml. This should match the vanilla name of entityclasses.xml

You may also want to remove their entries in entitygroups.xml and check if there's any association with a quest line that may give errors because they are missing.

**Comment by Turbero** [comment]
Not a bad idea. To be honest I created them when Alpha 17 was the latest. 

I'll review them. Thanks for the hint.

**Comment by Turbero** [comment]
Hello, SphereII

I upload a new version where the mods to remove animals are compatible with alpha18. I also added the ability to remove dogs, coyotes and mountain lions.

It works good so far. No errors in the log.

**New version: 1.0.0.5**

Feel free to give it a try: https://7dtdmodsdesktop.com/download.php

**Comment by Turbero** [comment]
Hello, SphereII

I upload a new version where the mods to remove animals are compatible with alpha18. I also added the ability to remove dogs, coyotes and mountain lions.

No errors in the log.

**New version: 1.0.0.5**

Feel free to give it a try: https://7dtdmodsdesktop.com/download.php
